# Generated by Django 5.1.5 on 2025-01-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_buyer_alter_commodity_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='avatar',
        ),
    ]
