# Generated by Django 5.1.5 on 2025-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_buyer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=32, verbose_name='店铺名称')),
                ('seller_name', models.CharField(max_length=32, verbose_name='联系人姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
