# Generated by Django 5.1.5 on 2025-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='店铺名称'),
        ),
    ]
