# Generated by Django 5.1.5 on 2025-02-14 05:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_commodity_photo_alter_seller_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='photo',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='商品价格'),
        ),
    ]
