# Generated by Django 5.1.5 on 2025-02-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_remove_commodity_photo_alter_commodity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
