# Generated by Django 5.1.5 on 2025-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_commodity_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='用户点击量'),
        ),
    ]
