# Generated by Django 5.1.5 on 2025-02-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_commodity_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
