# Generated by Django 5.1.5 on 2025-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_buyer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='label',
            field=models.SmallIntegerField(choices=[(1, '生活用品'), (2, '数码科技'), (3, '潮流轻奢'), (4, '时尚穿搭'), (5, '美妆个护'), (6, '食品生鲜'), (7, '运动户外'), (8, '图书文创')], default=1, verbose_name='标签'),
        ),
    ]
