# Generated by Django 5.1.5 on 2025-02-16 10:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_commodity_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='account',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='label',
            field=models.SmallIntegerField(choices=[(1, '居家生活'), (2, '数码科技'), (3, '潮流轻奢'), (4, '时尚穿搭'), (5, '美妆个护'), (6, '食品生鲜'), (7, '运动户外'), (8, '图书文创')], default=1, verbose_name='标签'),
        ),
    ]
