# Generated by Django 5.1.5 on 2025-02-17 00:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_buyer_account_alter_commodity_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='price_b',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='商品原价'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='商品现价'),
        ),
    ]
