# Generated by Django 5.1.5 on 2025-02-18 03:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_commodity_price_b_alter_commodity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='putaway_state',
            field=models.SmallIntegerField(choices=[(1, '已上架'), (2, '未上架')], default=1, verbose_name='上架状态'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_state', models.SmallIntegerField(choices=[(1, '已处理'), (2, '未处理')], default=1, verbose_name='订单处理状态')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('commodity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.commodity', verbose_name='商品')),
            ],
        ),
    ]
