# Generated by Django 5.1.5 on 2025-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_commodity_putaway_state_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(max_length=32, verbose_name='负责人姓名'),
        ),
    ]
