# Generated by Django 5.1.5 on 2025-02-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_seller_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='putaway_state',
            field=models.SmallIntegerField(choices=[(1, '上架'), (2, '下架')], default=2, verbose_name='上架状态'),
        ),
    ]
