# Generated by Django 5.1.5 on 2025-02-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_commodity_putaway_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=25.0, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='电动牙刷', max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_state',
            field=models.SmallIntegerField(choices=[(1, '未处理'), (2, '已处理')], default=1, verbose_name='订单处理状态'),
        ),
    ]
