# Generated by Django 5.1.5 on 2025-02-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_order_price_order_title_alter_order_process_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oid',
            field=models.CharField(default='202502110104', max_length=64, verbose_name='订单号'),
        ),
    ]
