# Generated by Django 5.1.5 on 2025-02-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_order_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='cart_state',
            field=models.SmallIntegerField(choices=[(1, '未添加'), (2, '已添加')], default=1, verbose_name='加入购物车'),
        ),
    ]
