# Generated by Django 5.1.5 on 2025-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_commodity_cart_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='account',
            field=models.FloatField(verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='putaway_state',
            field=models.SmallIntegerField(choices=[(1, '下架'), (2, '上架')], default=1, verbose_name='上架状态'),
        ),
    ]
