# Generated by Django 5.1.5 on 2025-02-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_buyer_account_alter_commodity_putaway_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.seller', verbose_name='店家'),
        ),
    ]
