# Generated by Django 5.1.5 on 2025-02-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_commodity_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.CharField(default='Tobbolc', max_length=32, verbose_name='买家'),
        ),
    ]
