# Generated by Django 5.1.5 on 2025-02-20 02:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_order_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commodity',
        ),
        migrations.AddField(
            model_name='order',
            name='commodity_id',
            field=models.IntegerField(default=1, verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='商品单价'),
        ),
    ]
