# Generated by Django 5.1.5 on 2025-02-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_remove_order_commodity_order_commodity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process_state',
            field=models.SmallIntegerField(choices=[(1, '未处理'), (2, '已拒绝'), (3, '已通过')], default=1, verbose_name='订单处理状态'),
        ),
    ]
