# Generated by Django 5.1.5 on 2025-02-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='label',
            field=models.SmallIntegerField(choices=[(1, '居家生活'), (2, '数码科技'), (3, '潮流轻奢'), (4, '时尚穿搭'), (5, '美妆个护'), (6, '食品生鲜'), (7, '运动户外'), (8, '图书文创')], default=1, verbose_name='标签'),
        ),
    ]
