# Generated by Django 5.1.5 on 2025-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_seller_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(default='生活王', max_length=32, verbose_name='卖家'),
        ),
    ]
