# Generated by Django 5.1.5 on 2025-02-21 18:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='正文内容')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
