# Generated by Django 5.1.5 on 2025-02-21 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_qamodel_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='detail',
            field=ckeditor.fields.RichTextField(default='这是一条商品详情内容', verbose_name='商品详情'),
        ),
    ]
