# Generated by Django 5.1.5 on 2025-02-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_commodity_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QAmodel',
        ),
    ]
