# Generated by Django 5.1.5 on 2025-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_delete_qamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='is_active',
            field=models.SmallIntegerField(choices=[(1, '激活'), (2, '冻结')], default=1, verbose_name='账户状态'),
        ),
    ]
