# Generated by Django 5.1.5 on 2025-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_commodity_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': '买家', 'verbose_name_plural': '买家'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': '卖家', 'verbose_name_plural': '卖家'},
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='is_active',
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_active',
            field=models.SmallIntegerField(choices=[(1, '激活'), (2, '冻结')], default=1, verbose_name='账户状态'),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.SmallIntegerField(choices=[(1, '激活'), (2, '冻结')], default=1, verbose_name='账户状态'),
        ),
    ]
